const path = require('path');
const express = require('express');
const app = require('./api/index');
const PORT = process.env.PORT || 3000;
app.use('/images', express.static(path.join(__dirname, 'images')));
app.use('/js', express.static(path.join(__dirname, 'js')));
app.use(express.static(path.join(__dirname)));
['index','about','service','work','faq','contact'].forEach(page=>app.get(`/${page}.html`,(req,res)=>res.sendFile(path.join(__dirname,`${page}.html`))));
app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));
if(process.env.NODE_ENV!=='production') app.listen(PORT,()=>console.log(`[AirLab] Running at http://localhost:${PORT}`));
module.exports=app;
